"""
mfw.py - A function that finds the most frequent k-mers in a given string
Date - 09/11/20
Author - Daniel Throop
Class - COSC 3090

"""

from collections import defaultdict

def getMax_kmers(string, k):
	counts = {}
	max_Vals = []

	for i in range((len(string) + 1) - k):
		current_kmer = string[i:(i+k)]
		if not(current_kmer in counts):
			counts[current_kmer] = 0

		counts[current_kmer] += 1

	max_Vals = [k for k, v in counts.items() if v == max(counts.values())]


	return max_Vals
	

# cases from PDF

# print(getMax_kmers("ACGTTGCATGTCGCATGATGCATGAGAGCT", 4))

# print(getMax_kmers("TGGTAGCGACGTTGGTCCCGCCGCTTGAGAATCTGGATGAACATAAGCTCCCACTTGGCTTATTCAGAGAACTGGTCAACACTTGTCTCTCCCAGCCAGGTCTGACCACCGGGCAACTTTTAGAGCACTATCGTGGTACAAATAATGCTGCCAC", 3))

# print(getMax_kmers("CAGTGGCAGATGACATTTTGCTGGTCGACTGGTTACAACAACGCCTGGGGCTTTTGAGCAACGAGACTTTTCAATGTTGCACCGTTTGCTGCATGATATTGAAAACAATATCACCAAATAAATAACGCCTTAGTAAGTAGCTTTT", 4))

# print(getMax_kmers("ATACAATTACAGTCTGGAACCGGATGAACTGGCCGCAGGTTAACAACAGAGTTGCCAGGCACTGCCGCTGACCAGCAACAACAACAATGACTTTGACGCGAAGGGGATGGCATGAGCGAACTGATCGTCAGCCGTCAGCAACGAGTATTGTTGCTGACCCTTAACAATCCCGCCGCACGTAATGCGCTAACTAATGCCCTGCTG", 5))

# print(getMax_kmers("CCAGCGGGGGTTGATGCTCTGGGGGTCACAAGATTGCATTTTTATGGGGTTGCAAAAATGTTTTTTACGGCAGATTCATTTAAAATGCCCACTGGCTGGAGACATAGCCCGGATGCGCGTCTTTTACAACGTATTGCGGGGTAAAATCGTAGATGTTTTAAAATAGGCGTAAC", 5))








